### ISSUE TITLE
Case non trouvée

### ISSUE THREAD

**Issue by JojoAz1605** [JojoAz1605/Simplification-Grille-Tkinter#10]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\noctu\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1884, in __call__
    return self.func(*args)
  File "C:\Users\noctu\Desktop\Programmation\Python\Simplification-Grille-Tkinter\objGrille.py", line 97, in cycleState
    case.cycleState()
AttributeError: 'NoneType' object has no attribute 'cycleState'

**Comment by JojoAz1605** [comment]
Après 2-3 petit calculs, l'erreur vient en fait du fait que la case soit cherchée dans un rayon de la moitié de la taille d'une case.
J'étais donc en train d'essayer de faire une hitbox en rayon avec un carré, logique :)
Donc solution: passé sur un repérage par intervalle
